### PR TITLE
Remove waypoiny decimals

### PR DESCRIPTION
**Pull request by tacotexmex**
for a cleaner HUD look

### CODE REVIEW

**Comment by SmallJoker** [comment]
How do I test this change? `/named_waypoints` seems to return a formspec with empty string due to lack of existing data... which is supposed to be created by this formspec, right?

**Comment by tacotexmex** [comment]
You would need to test with a mod that depends on this one. fantasy_settlements for example.

**Comment by SmallJoker** [comment]
I cannot find any such mod on CDB or the forum. Either way, the change is trivial and looks okay, thus I will merge it in a few days unless there are objections.

**Comment by tacotexmex** [comment]
Nice. It’s https://github.com/FaceDeer/settlements_fantasy :)

**Pull request merged**
